clear screen
@clean
set termout off
conn dbdemo/dbdemo@db23
set termout off
drop user jane_doe cascade;
drop domain amex ;
@drop t1
@drop credit_card
@drop emp2
drop table hr.new_table purge;
alter session set group_by_position_enabled = false;
@drop t
@drop person
alter table products modify total_sold not reservable;
@drop products
@drop seq
@drop myemp
@drop customer
@drop orders
@drop orderitems
col journal new_value journal_table
col journal format a30
set verify off
drop view orders_ov;
@dropc order_items
create or replace
function my_plsql_func return number is
begin
  return 10;
end;
/
create sequence seq;
col first_name format a20
col last_name format a20

col annotation_name format a30
col annotation_value format a30
       
clear screen
set termout on
set echo off
prompt |
prompt |     _    _   _ _   _  ___ _____  _  _____ ___ ___  _   _ ____  
prompt |    / \  | \ | | \ | |/ _ \_   _|/ \|_   _|_ _/ _ \| \ | / ___| 
prompt |   / _ \ |  \| |  \| | | | || | / _ \ | |  | | | | |  \| \___ \ 
prompt |  / ___ \| |\  | |\  | |_| || |/ ___ \| |  | | |_| | |\  |___) |
prompt | /_/   \_\_| \_|_| \_|\___/ |_/_/   \_\_| |___\___/|_| \_|____/ 
prompt |                                                                
prompt |
pause
set echo on
clear screen

set echo on
set termout on
create table person
 ( pid int,
   first_name  varchar2(20),
   last_name   varchar2(20),
   mobile      varchar2(30),
   sms_allowed boolean,
   birth_date  date,
   credit_card varchar2(10),
   email_adress varchar2(20)
 );
pause
clear screen
comment on table person               is 'Employee list';
pause
comment on column person.pid          is 'PID is the primary key as generated by sequence';
pause
comment on column person.first_name   is 'Upper case preferred';
pause
comment on column person.last_name    is 'Upper case preferred';
pause
comment on column person.mobile       is 'Not to be shown unless sms text is allowed';
pause
comment on column person.birth_date   is 'Not to be shown unless sms text is allowed';
pause
comment on column person.credit_card  is 'Should be redacted at all times';
pause
comment on column person.email_adress is 'Leading part should be redacted except for admins';
pause
clear screen
alter table person modify pid          
  annotations (PrimaryKey, Sequence, Display 'Never');
pause  
alter table person modify first_name   
  annotations (Case 'Upper', UTF8);
pause  
alter table person modify last_name    
  annotations (Case 'Upper', UTF8);
pause  
alter table person modify credit_card  
  annotations (Display 'Redact', Sensitive);
pause  
alter table person modify email_adress 
  annotations (Sensitive);
pause  
clear screen  
alter table person modify email_adress 
  annotations (add Display 'RedactPartial');
pause  
alter table person modify email_adress 
  annotations (add Display 'RedactPartial');  
pause
clear screen
select column_name,
       annotation_name,
       annotation_value
from   user_annotations_usage
where  object_name = 'PERSON';
pause
desc person
pause
set describe annotation on
desc person

pause Done
