-------------------------------------------------------------------------------
--
-- PLEASE NOTE
-- 
-- No warranty, no liability, no support.
--
-- This script is 100% at your own risk to use.
--
-------------------------------------------------------------------------------
drop table customers purge;
create table customers 
 ( cust_id int,
   first_name varchar2(50),
   last_name  varchar2(50)
  );   

insert into customers (cust_id,first_name,last_name) values (100,'Steven','King');
insert into customers (cust_id,first_name,last_name) values (101,'Neena','Kochhar');
insert into customers (cust_id,first_name,last_name) values (102,'Lex','De Haan');
insert into customers (cust_id,first_name,last_name) values (103,'Alexander','Hunold');
insert into customers (cust_id,first_name,last_name) values (104,'Bruce','Ernst');
insert into customers (cust_id,first_name,last_name) values (105,'David','Austin');
insert into customers (cust_id,first_name,last_name) values (106,'Valli','Pataballa');
insert into customers (cust_id,first_name,last_name) values (107,'Diana','Lorentz');
insert into customers (cust_id,first_name,last_name) values (108,'Nancy','Greenberg');
insert into customers (cust_id,first_name,last_name) values (109,'Daniel','Faviet');
insert into customers (cust_id,first_name,last_name) values (110,'John','Chen');
insert into customers (cust_id,first_name,last_name) values (111,'Ismael','Sciarra');
insert into customers (cust_id,first_name,last_name) values (112,'Jose Manuel','Urman');
insert into customers (cust_id,first_name,last_name) values (113,'Luis','Popp');
insert into customers (cust_id,first_name,last_name) values (114,'Den','Raphaely');
insert into customers (cust_id,first_name,last_name) values (115,'Alexander','Khoo');
insert into customers (cust_id,first_name,last_name) values (116,'Shelli','Baida');
insert into customers (cust_id,first_name,last_name) values (117,'Sigal','Tobias');
insert into customers (cust_id,first_name,last_name) values (118,'Guy','Himuro');
insert into customers (cust_id,first_name,last_name) values (119,'Karen','Colmenares');
insert into customers (cust_id,first_name,last_name) values (120,'Matthew','Weiss');
insert into customers (cust_id,first_name,last_name) values (121,'Adam','Fripp');
insert into customers (cust_id,first_name,last_name) values (122,'Payam','Kaufling');
insert into customers (cust_id,first_name,last_name) values (123,'Shanta','Vollman');
insert into customers (cust_id,first_name,last_name) values (124,'Kevin','Mourgos');
insert into customers (cust_id,first_name,last_name) values (125,'Julia','Nayer');
insert into customers (cust_id,first_name,last_name) values (126,'Irene','Mikkilineni');
insert into customers (cust_id,first_name,last_name) values (127,'James','Landry');
insert into customers (cust_id,first_name,last_name) values (128,'Steven','Markle');
insert into customers (cust_id,first_name,last_name) values (129,'Laura','Bissot');
insert into customers (cust_id,first_name,last_name) values (130,'Mozhe','Atkinson');
insert into customers (cust_id,first_name,last_name) values (131,'James','Marlow');
insert into customers (cust_id,first_name,last_name) values (132,'TJ','Olson');
insert into customers (cust_id,first_name,last_name) values (133,'Jason','Mallin');
insert into customers (cust_id,first_name,last_name) values (134,'Michael','Rogers');
insert into customers (cust_id,first_name,last_name) values (135,'Ki','Gee');
insert into customers (cust_id,first_name,last_name) values (136,'Hazel','Philtanker');
insert into customers (cust_id,first_name,last_name) values (137,'Renske','Ladwig');
insert into customers (cust_id,first_name,last_name) values (138,'Stephen','Stiles');
insert into customers (cust_id,first_name,last_name) values (139,'John','Seo');
insert into customers (cust_id,first_name,last_name) values (140,'Joshua','Patel');
insert into customers (cust_id,first_name,last_name) values (141,'Trenna','Rajs');
insert into customers (cust_id,first_name,last_name) values (142,'Curtis','Davies');
insert into customers (cust_id,first_name,last_name) values (143,'Randall','Matos');
insert into customers (cust_id,first_name,last_name) values (144,'Peter','Vargas');
insert into customers (cust_id,first_name,last_name) values (145,'John','Russell');
insert into customers (cust_id,first_name,last_name) values (146,'Karen','Partners');
insert into customers (cust_id,first_name,last_name) values (147,'Alberto','Errazuriz');
insert into customers (cust_id,first_name,last_name) values (148,'Gerald','Cambrault');
insert into customers (cust_id,first_name,last_name) values (149,'Eleni','Zlotkey');
insert into customers (cust_id,first_name,last_name) values (150,'Peter','Tucker');
insert into customers (cust_id,first_name,last_name) values (151,'David','Bernstein');
insert into customers (cust_id,first_name,last_name) values (152,'Peter','Hall');
insert into customers (cust_id,first_name,last_name) values (153,'Christopher','Olsen');
insert into customers (cust_id,first_name,last_name) values (154,'Nanette','Cambrault');
insert into customers (cust_id,first_name,last_name) values (155,'Oliver','Tuvault');
insert into customers (cust_id,first_name,last_name) values (156,'Janette','King');
insert into customers (cust_id,first_name,last_name) values (157,'Patrick','Sully');
insert into customers (cust_id,first_name,last_name) values (158,'Allan','McEwen');
insert into customers (cust_id,first_name,last_name) values (159,'Lindsey','Smith');
insert into customers (cust_id,first_name,last_name) values (160,'Louise','Doran');
insert into customers (cust_id,first_name,last_name) values (161,'Sarath','Sewall');
insert into customers (cust_id,first_name,last_name) values (162,'Clara','Vishney');
insert into customers (cust_id,first_name,last_name) values (163,'Danielle','Greene');
insert into customers (cust_id,first_name,last_name) values (164,'Mattea','Marvins');
insert into customers (cust_id,first_name,last_name) values (165,'David','Lee');
insert into customers (cust_id,first_name,last_name) values (166,'Sundar','Ande');
insert into customers (cust_id,first_name,last_name) values (167,'Amit','Banda');
insert into customers (cust_id,first_name,last_name) values (168,'Lisa','Ozer');
insert into customers (cust_id,first_name,last_name) values (169,'Harrison','Bloom');
insert into customers (cust_id,first_name,last_name) values (170,'Tayler','Fox');
insert into customers (cust_id,first_name,last_name) values (171,'William','Smith');
insert into customers (cust_id,first_name,last_name) values (172,'Elizabeth','Bates');
insert into customers (cust_id,first_name,last_name) values (173,'Sundita','Kumar');
insert into customers (cust_id,first_name,last_name) values (174,'Ellen','Abel');
insert into customers (cust_id,first_name,last_name) values (175,'Alyssa','Hutton');
insert into customers (cust_id,first_name,last_name) values (176,'Jonathon','Taylor');
insert into customers (cust_id,first_name,last_name) values (177,'Jack','Livingston');
insert into customers (cust_id,first_name,last_name) values (178,'Kimberely','Grant');
insert into customers (cust_id,first_name,last_name) values (179,'Charles','Johnson');
insert into customers (cust_id,first_name,last_name) values (180,'Winston','Taylor');
insert into customers (cust_id,first_name,last_name) values (181,'Jean','Fleaur');
insert into customers (cust_id,first_name,last_name) values (182,'Martha','Sullivan');
insert into customers (cust_id,first_name,last_name) values (183,'Girard','Geoni');
insert into customers (cust_id,first_name,last_name) values (184,'Nandita','Sarchand');
insert into customers (cust_id,first_name,last_name) values (185,'Alexis','Bull');
insert into customers (cust_id,first_name,last_name) values (186,'Julia','Dellinger');
insert into customers (cust_id,first_name,last_name) values (187,'Anthony','Cabrio');
insert into customers (cust_id,first_name,last_name) values (188,'Kelly','Chung');
insert into customers (cust_id,first_name,last_name) values (189,'Jennifer','Dilly');
insert into customers (cust_id,first_name,last_name) values (190,'Timothy','Gates');
insert into customers (cust_id,first_name,last_name) values (191,'Randall','Perkins');
insert into customers (cust_id,first_name,last_name) values (192,'Sarah','Bell');
insert into customers (cust_id,first_name,last_name) values (193,'Britney','Everett');
insert into customers (cust_id,first_name,last_name) values (194,'Samuel','McCain');
insert into customers (cust_id,first_name,last_name) values (195,'Vance','Jones');
insert into customers (cust_id,first_name,last_name) values (196,'Alana','Walsh');
insert into customers (cust_id,first_name,last_name) values (197,'Kevin','Feeney');
insert into customers (cust_id,first_name,last_name) values (198,'Donald','OConnell');
insert into customers (cust_id,first_name,last_name) values (199,'Douglas','Grant');


select USED_UREC
from   V$TRANSACTION;

rollback;

create index CUST_IX on CUSTOMERS ( cust_id );

insert into customers (cust_id,first_name,last_name) values (100,'Steven','King');
insert into customers (cust_id,first_name,last_name) values (101,'Neena','Kochhar');
insert into customers (cust_id,first_name,last_name) values (102,'Lex','De Haan');
insert into customers (cust_id,first_name,last_name) values (103,'Alexander','Hunold');
insert into customers (cust_id,first_name,last_name) values (104,'Bruce','Ernst');
insert into customers (cust_id,first_name,last_name) values (105,'David','Austin');
insert into customers (cust_id,first_name,last_name) values (106,'Valli','Pataballa');
insert into customers (cust_id,first_name,last_name) values (107,'Diana','Lorentz');
insert into customers (cust_id,first_name,last_name) values (108,'Nancy','Greenberg');
insert into customers (cust_id,first_name,last_name) values (109,'Daniel','Faviet');
insert into customers (cust_id,first_name,last_name) values (110,'John','Chen');
insert into customers (cust_id,first_name,last_name) values (111,'Ismael','Sciarra');
insert into customers (cust_id,first_name,last_name) values (112,'Jose Manuel','Urman');
insert into customers (cust_id,first_name,last_name) values (113,'Luis','Popp');
insert into customers (cust_id,first_name,last_name) values (114,'Den','Raphaely');
insert into customers (cust_id,first_name,last_name) values (115,'Alexander','Khoo');
insert into customers (cust_id,first_name,last_name) values (116,'Shelli','Baida');
insert into customers (cust_id,first_name,last_name) values (117,'Sigal','Tobias');
insert into customers (cust_id,first_name,last_name) values (118,'Guy','Himuro');
insert into customers (cust_id,first_name,last_name) values (119,'Karen','Colmenares');
insert into customers (cust_id,first_name,last_name) values (120,'Matthew','Weiss');
insert into customers (cust_id,first_name,last_name) values (121,'Adam','Fripp');
insert into customers (cust_id,first_name,last_name) values (122,'Payam','Kaufling');
insert into customers (cust_id,first_name,last_name) values (123,'Shanta','Vollman');
insert into customers (cust_id,first_name,last_name) values (124,'Kevin','Mourgos');
insert into customers (cust_id,first_name,last_name) values (125,'Julia','Nayer');
insert into customers (cust_id,first_name,last_name) values (126,'Irene','Mikkilineni');
insert into customers (cust_id,first_name,last_name) values (127,'James','Landry');
insert into customers (cust_id,first_name,last_name) values (128,'Steven','Markle');
insert into customers (cust_id,first_name,last_name) values (129,'Laura','Bissot');
insert into customers (cust_id,first_name,last_name) values (130,'Mozhe','Atkinson');
insert into customers (cust_id,first_name,last_name) values (131,'James','Marlow');
insert into customers (cust_id,first_name,last_name) values (132,'TJ','Olson');
insert into customers (cust_id,first_name,last_name) values (133,'Jason','Mallin');
insert into customers (cust_id,first_name,last_name) values (134,'Michael','Rogers');
insert into customers (cust_id,first_name,last_name) values (135,'Ki','Gee');
insert into customers (cust_id,first_name,last_name) values (136,'Hazel','Philtanker');
insert into customers (cust_id,first_name,last_name) values (137,'Renske','Ladwig');
insert into customers (cust_id,first_name,last_name) values (138,'Stephen','Stiles');
insert into customers (cust_id,first_name,last_name) values (139,'John','Seo');
insert into customers (cust_id,first_name,last_name) values (140,'Joshua','Patel');
insert into customers (cust_id,first_name,last_name) values (141,'Trenna','Rajs');
insert into customers (cust_id,first_name,last_name) values (142,'Curtis','Davies');
insert into customers (cust_id,first_name,last_name) values (143,'Randall','Matos');
insert into customers (cust_id,first_name,last_name) values (144,'Peter','Vargas');
insert into customers (cust_id,first_name,last_name) values (145,'John','Russell');
insert into customers (cust_id,first_name,last_name) values (146,'Karen','Partners');
insert into customers (cust_id,first_name,last_name) values (147,'Alberto','Errazuriz');
insert into customers (cust_id,first_name,last_name) values (148,'Gerald','Cambrault');
insert into customers (cust_id,first_name,last_name) values (149,'Eleni','Zlotkey');
insert into customers (cust_id,first_name,last_name) values (150,'Peter','Tucker');
insert into customers (cust_id,first_name,last_name) values (151,'David','Bernstein');
insert into customers (cust_id,first_name,last_name) values (152,'Peter','Hall');
insert into customers (cust_id,first_name,last_name) values (153,'Christopher','Olsen');
insert into customers (cust_id,first_name,last_name) values (154,'Nanette','Cambrault');
insert into customers (cust_id,first_name,last_name) values (155,'Oliver','Tuvault');
insert into customers (cust_id,first_name,last_name) values (156,'Janette','King');
insert into customers (cust_id,first_name,last_name) values (157,'Patrick','Sully');
insert into customers (cust_id,first_name,last_name) values (158,'Allan','McEwen');
insert into customers (cust_id,first_name,last_name) values (159,'Lindsey','Smith');
insert into customers (cust_id,first_name,last_name) values (160,'Louise','Doran');
insert into customers (cust_id,first_name,last_name) values (161,'Sarath','Sewall');
insert into customers (cust_id,first_name,last_name) values (162,'Clara','Vishney');
insert into customers (cust_id,first_name,last_name) values (163,'Danielle','Greene');
insert into customers (cust_id,first_name,last_name) values (164,'Mattea','Marvins');
insert into customers (cust_id,first_name,last_name) values (165,'David','Lee');
insert into customers (cust_id,first_name,last_name) values (166,'Sundar','Ande');
insert into customers (cust_id,first_name,last_name) values (167,'Amit','Banda');
insert into customers (cust_id,first_name,last_name) values (168,'Lisa','Ozer');
insert into customers (cust_id,first_name,last_name) values (169,'Harrison','Bloom');
insert into customers (cust_id,first_name,last_name) values (170,'Tayler','Fox');
insert into customers (cust_id,first_name,last_name) values (171,'William','Smith');
insert into customers (cust_id,first_name,last_name) values (172,'Elizabeth','Bates');
insert into customers (cust_id,first_name,last_name) values (173,'Sundita','Kumar');
insert into customers (cust_id,first_name,last_name) values (174,'Ellen','Abel');
insert into customers (cust_id,first_name,last_name) values (175,'Alyssa','Hutton');
insert into customers (cust_id,first_name,last_name) values (176,'Jonathon','Taylor');
insert into customers (cust_id,first_name,last_name) values (177,'Jack','Livingston');
insert into customers (cust_id,first_name,last_name) values (178,'Kimberely','Grant');
insert into customers (cust_id,first_name,last_name) values (179,'Charles','Johnson');
insert into customers (cust_id,first_name,last_name) values (180,'Winston','Taylor');
insert into customers (cust_id,first_name,last_name) values (181,'Jean','Fleaur');
insert into customers (cust_id,first_name,last_name) values (182,'Martha','Sullivan');
insert into customers (cust_id,first_name,last_name) values (183,'Girard','Geoni');
insert into customers (cust_id,first_name,last_name) values (184,'Nandita','Sarchand');
insert into customers (cust_id,first_name,last_name) values (185,'Alexis','Bull');
insert into customers (cust_id,first_name,last_name) values (186,'Julia','Dellinger');
insert into customers (cust_id,first_name,last_name) values (187,'Anthony','Cabrio');
insert into customers (cust_id,first_name,last_name) values (188,'Kelly','Chung');
insert into customers (cust_id,first_name,last_name) values (189,'Jennifer','Dilly');
insert into customers (cust_id,first_name,last_name) values (190,'Timothy','Gates');
insert into customers (cust_id,first_name,last_name) values (191,'Randall','Perkins');
insert into customers (cust_id,first_name,last_name) values (192,'Sarah','Bell');
insert into customers (cust_id,first_name,last_name) values (193,'Britney','Everett');
insert into customers (cust_id,first_name,last_name) values (194,'Samuel','McCain');
insert into customers (cust_id,first_name,last_name) values (195,'Vance','Jones');
insert into customers (cust_id,first_name,last_name) values (196,'Alana','Walsh');
insert into customers (cust_id,first_name,last_name) values (197,'Kevin','Feeney');
insert into customers (cust_id,first_name,last_name) values (198,'Donald','OConnell');
insert into customers (cust_id,first_name,last_name) values (199,'Douglas','Grant');


select USED_UREC
from   V$TRANSACTION;

rollback;

create index CUST_IX2 on CUSTOMERS ( first_name );
create index CUST_IX3 on CUSTOMERS ( last_name );

insert into customers (cust_id,first_name,last_name) values (100,'Steven','King');
insert into customers (cust_id,first_name,last_name) values (101,'Neena','Kochhar');
insert into customers (cust_id,first_name,last_name) values (102,'Lex','De Haan');
insert into customers (cust_id,first_name,last_name) values (103,'Alexander','Hunold');
insert into customers (cust_id,first_name,last_name) values (104,'Bruce','Ernst');
insert into customers (cust_id,first_name,last_name) values (105,'David','Austin');
insert into customers (cust_id,first_name,last_name) values (106,'Valli','Pataballa');
insert into customers (cust_id,first_name,last_name) values (107,'Diana','Lorentz');
insert into customers (cust_id,first_name,last_name) values (108,'Nancy','Greenberg');
insert into customers (cust_id,first_name,last_name) values (109,'Daniel','Faviet');
insert into customers (cust_id,first_name,last_name) values (110,'John','Chen');
insert into customers (cust_id,first_name,last_name) values (111,'Ismael','Sciarra');
insert into customers (cust_id,first_name,last_name) values (112,'Jose Manuel','Urman');
insert into customers (cust_id,first_name,last_name) values (113,'Luis','Popp');
insert into customers (cust_id,first_name,last_name) values (114,'Den','Raphaely');
insert into customers (cust_id,first_name,last_name) values (115,'Alexander','Khoo');
insert into customers (cust_id,first_name,last_name) values (116,'Shelli','Baida');
insert into customers (cust_id,first_name,last_name) values (117,'Sigal','Tobias');
insert into customers (cust_id,first_name,last_name) values (118,'Guy','Himuro');
insert into customers (cust_id,first_name,last_name) values (119,'Karen','Colmenares');
insert into customers (cust_id,first_name,last_name) values (120,'Matthew','Weiss');
insert into customers (cust_id,first_name,last_name) values (121,'Adam','Fripp');
insert into customers (cust_id,first_name,last_name) values (122,'Payam','Kaufling');
insert into customers (cust_id,first_name,last_name) values (123,'Shanta','Vollman');
insert into customers (cust_id,first_name,last_name) values (124,'Kevin','Mourgos');
insert into customers (cust_id,first_name,last_name) values (125,'Julia','Nayer');
insert into customers (cust_id,first_name,last_name) values (126,'Irene','Mikkilineni');
insert into customers (cust_id,first_name,last_name) values (127,'James','Landry');
insert into customers (cust_id,first_name,last_name) values (128,'Steven','Markle');
insert into customers (cust_id,first_name,last_name) values (129,'Laura','Bissot');
insert into customers (cust_id,first_name,last_name) values (130,'Mozhe','Atkinson');
insert into customers (cust_id,first_name,last_name) values (131,'James','Marlow');
insert into customers (cust_id,first_name,last_name) values (132,'TJ','Olson');
insert into customers (cust_id,first_name,last_name) values (133,'Jason','Mallin');
insert into customers (cust_id,first_name,last_name) values (134,'Michael','Rogers');
insert into customers (cust_id,first_name,last_name) values (135,'Ki','Gee');
insert into customers (cust_id,first_name,last_name) values (136,'Hazel','Philtanker');
insert into customers (cust_id,first_name,last_name) values (137,'Renske','Ladwig');
insert into customers (cust_id,first_name,last_name) values (138,'Stephen','Stiles');
insert into customers (cust_id,first_name,last_name) values (139,'John','Seo');
insert into customers (cust_id,first_name,last_name) values (140,'Joshua','Patel');
insert into customers (cust_id,first_name,last_name) values (141,'Trenna','Rajs');
insert into customers (cust_id,first_name,last_name) values (142,'Curtis','Davies');
insert into customers (cust_id,first_name,last_name) values (143,'Randall','Matos');
insert into customers (cust_id,first_name,last_name) values (144,'Peter','Vargas');
insert into customers (cust_id,first_name,last_name) values (145,'John','Russell');
insert into customers (cust_id,first_name,last_name) values (146,'Karen','Partners');
insert into customers (cust_id,first_name,last_name) values (147,'Alberto','Errazuriz');
insert into customers (cust_id,first_name,last_name) values (148,'Gerald','Cambrault');
insert into customers (cust_id,first_name,last_name) values (149,'Eleni','Zlotkey');
insert into customers (cust_id,first_name,last_name) values (150,'Peter','Tucker');
insert into customers (cust_id,first_name,last_name) values (151,'David','Bernstein');
insert into customers (cust_id,first_name,last_name) values (152,'Peter','Hall');
insert into customers (cust_id,first_name,last_name) values (153,'Christopher','Olsen');
insert into customers (cust_id,first_name,last_name) values (154,'Nanette','Cambrault');
insert into customers (cust_id,first_name,last_name) values (155,'Oliver','Tuvault');
insert into customers (cust_id,first_name,last_name) values (156,'Janette','King');
insert into customers (cust_id,first_name,last_name) values (157,'Patrick','Sully');
insert into customers (cust_id,first_name,last_name) values (158,'Allan','McEwen');
insert into customers (cust_id,first_name,last_name) values (159,'Lindsey','Smith');
insert into customers (cust_id,first_name,last_name) values (160,'Louise','Doran');
insert into customers (cust_id,first_name,last_name) values (161,'Sarath','Sewall');
insert into customers (cust_id,first_name,last_name) values (162,'Clara','Vishney');
insert into customers (cust_id,first_name,last_name) values (163,'Danielle','Greene');
insert into customers (cust_id,first_name,last_name) values (164,'Mattea','Marvins');
insert into customers (cust_id,first_name,last_name) values (165,'David','Lee');
insert into customers (cust_id,first_name,last_name) values (166,'Sundar','Ande');
insert into customers (cust_id,first_name,last_name) values (167,'Amit','Banda');
insert into customers (cust_id,first_name,last_name) values (168,'Lisa','Ozer');
insert into customers (cust_id,first_name,last_name) values (169,'Harrison','Bloom');
insert into customers (cust_id,first_name,last_name) values (170,'Tayler','Fox');
insert into customers (cust_id,first_name,last_name) values (171,'William','Smith');
insert into customers (cust_id,first_name,last_name) values (172,'Elizabeth','Bates');
insert into customers (cust_id,first_name,last_name) values (173,'Sundita','Kumar');
insert into customers (cust_id,first_name,last_name) values (174,'Ellen','Abel');
insert into customers (cust_id,first_name,last_name) values (175,'Alyssa','Hutton');
insert into customers (cust_id,first_name,last_name) values (176,'Jonathon','Taylor');
insert into customers (cust_id,first_name,last_name) values (177,'Jack','Livingston');
insert into customers (cust_id,first_name,last_name) values (178,'Kimberely','Grant');
insert into customers (cust_id,first_name,last_name) values (179,'Charles','Johnson');
insert into customers (cust_id,first_name,last_name) values (180,'Winston','Taylor');
insert into customers (cust_id,first_name,last_name) values (181,'Jean','Fleaur');
insert into customers (cust_id,first_name,last_name) values (182,'Martha','Sullivan');
insert into customers (cust_id,first_name,last_name) values (183,'Girard','Geoni');
insert into customers (cust_id,first_name,last_name) values (184,'Nandita','Sarchand');
insert into customers (cust_id,first_name,last_name) values (185,'Alexis','Bull');
insert into customers (cust_id,first_name,last_name) values (186,'Julia','Dellinger');
insert into customers (cust_id,first_name,last_name) values (187,'Anthony','Cabrio');
insert into customers (cust_id,first_name,last_name) values (188,'Kelly','Chung');
insert into customers (cust_id,first_name,last_name) values (189,'Jennifer','Dilly');
insert into customers (cust_id,first_name,last_name) values (190,'Timothy','Gates');
insert into customers (cust_id,first_name,last_name) values (191,'Randall','Perkins');
insert into customers (cust_id,first_name,last_name) values (192,'Sarah','Bell');
insert into customers (cust_id,first_name,last_name) values (193,'Britney','Everett');
insert into customers (cust_id,first_name,last_name) values (194,'Samuel','McCain');
insert into customers (cust_id,first_name,last_name) values (195,'Vance','Jones');
insert into customers (cust_id,first_name,last_name) values (196,'Alana','Walsh');
insert into customers (cust_id,first_name,last_name) values (197,'Kevin','Feeney');
insert into customers (cust_id,first_name,last_name) values (198,'Donald','OConnell');
insert into customers (cust_id,first_name,last_name) values (199,'Douglas','Grant');


select USED_UREC
from   V$TRANSACTION;

drop table CUSTOMERS purge;

